load("//ReactNative:DEFS.bzl", "react_native_dep", "react_native_target", "rn_android_library")

rn_android_library(
    name = "timepicker",
    srcs = glob(["**/*.java"]),
    provided_deps = [

    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/android/support-annotations:android-support-annotations"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
    ],
)
